import { AttributeDiff, PlanSummary, ResourceChangeSummary } from './types';

export const DEFAULT_COMMENT_MARKER = '<!-- tf-plan-comment -->';
const GITHUB_COMMENT_MAX_LENGTH = 65536;

const ACTION_EMOJI: Record<string, string> = {
  create: '🟢',
  update: '🟡',
  delete: '🔴',
  replace: '🔄',
};

function escapeInlineCode(text: string): string {
  return text.replace(/`/g, '\\`');
}

function formatAttributeDiffs(diffs: AttributeDiff[]): string {
  if (diffs.length === 0) {
    return '_No attribute changes detected._\n';
  }

  const lines = diffs.map((diff) => {
    const path = `\`${escapeInlineCode(diff.path)}\``;
    const before = diff.before.includes('\n')
      ? `\n\`\`\`\n${diff.before}\n\`\`\``
      : `\`${escapeInlineCode(diff.before)}\``;
    const after = diff.after.includes('\n')
      ? `\n\`\`\`\n${diff.after}\n\`\`\``
      : `\`${escapeInlineCode(diff.after)}\``;
    return `- **${path}**: ${before} → ${after}`;
  });

  return lines.join('\n') + '\n';
}

function formatResourceSection(resource: ResourceChangeSummary): string {
  const emoji = ACTION_EMOJI[resource.action] ?? '⚪';
  const actionLabel = resource.action.charAt(0).toUpperCase() + resource.action.slice(1);
  const reason = resource.actionReason
    ? ` _(${resource.actionReason.replace(/_/g, ' ')})_`
    : '';

  let body = '';
  if (resource.action === 'create') {
    body = '_New resource — no prior state._\n';
    if (resource.attributeDiffs.length > 0) {
      body += '\n**Planned attributes:**\n' + formatAttributeDiffs(resource.attributeDiffs);
    }
  } else if (resource.action === 'delete') {
    body = '_Resource will be destroyed._\n';
  } else {
    body = formatAttributeDiffs(resource.attributeDiffs);
  }

  return `<details>
<summary>${emoji} <code>${resource.address}</code> — ${actionLabel}${reason}</summary>

**Type:** \`${resource.type}\`

${body}
</details>`;
}

export function formatPlanComment(summary: PlanSummary, marker: string = DEFAULT_COMMENT_MARKER): string {
  const createCount = summary.toCreate.length;
  const updateCount = summary.toUpdate.length;
  const destroyCount = summary.toDestroy.length;
  const replaceCount = summary.toReplace.length;
  const totalChanges = createCount + updateCount + destroyCount + replaceCount;

  const parts: string[] = [marker, '## Terraform Plan Summary', ''];

  if (totalChanges === 0) {
    parts.push('✅ **No changes.** Your infrastructure matches the configuration.');
    return parts.join('\n');
  }

  const summaryParts: string[] = [];
  if (createCount > 0) {
    summaryParts.push(`🟢 **${createCount}** to add`);
  }
  if (updateCount > 0) {
    summaryParts.push(`🟡 **${updateCount}** to change`);
  }
  if (replaceCount > 0) {
    summaryParts.push(`🔄 **${replaceCount}** to replace`);
  }
  if (destroyCount > 0) {
    summaryParts.push(`🔴 **${destroyCount}** to destroy`);
  }

  parts.push(summaryParts.join(' · '));
  parts.push('');

  if (destroyCount > 0 || replaceCount > 0) {
    parts.push('> ⚠️ **Destructive changes detected** — review carefully before merging.');
    parts.push('');
  }

  const sections: ResourceChangeSummary[] = [
    ...summary.toDestroy,
    ...summary.toReplace,
    ...summary.toUpdate,
    ...summary.toCreate,
  ];

  for (const resource of sections) {
    parts.push(formatResourceSection(resource));
    parts.push('');
  }

  parts.push('---');
  parts.push('_Generated by [TF Plan Comment](https://github.com/patrickmackin/tf-plan-comment)_');

  let comment = parts.join('\n');

  if (comment.length > GITHUB_COMMENT_MAX_LENGTH) {
    const truncated = comment.slice(0, GITHUB_COMMENT_MAX_LENGTH - 200);
    comment =
      truncated +
      '\n\n---\n\n⚠️ _Comment truncated — plan output exceeds GitHub comment size limit._';
  }

  return comment;
}
